// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: internal/proto/lock.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_proto_lock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_lock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_lock_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_proto_lock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_lock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_lock_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Read          bool                   `protobuf:"varint,1,opt,name=read,proto3" json:"read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_internal_proto_lock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_lock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_lock_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRequest) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	CurrData      int64                  `protobuf:"varint,2,opt,name=curr_data,json=currData,proto3" json:"curr_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_internal_proto_lock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_lock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_lock_proto_rawDescGZIP(), []int{3}
}

func (x *ReadResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ReadResponse) GetCurrData() int64 {
	if x != nil {
		return x.CurrData
	}
	return 0
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Val           int64                  `protobuf:"varint,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_internal_proto_lock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_lock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_lock_proto_rawDescGZIP(), []int{4}
}

func (x *WriteRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *WriteRequest) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	UpdatedData   int64                  `protobuf:"varint,2,opt,name=updated_data,json=updatedData,proto3" json:"updated_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_internal_proto_lock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_lock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_lock_proto_rawDescGZIP(), []int{5}
}

func (x *WriteResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *WriteResponse) GetUpdatedData() int64 {
	if x != nil {
		return x.UpdatedData
	}
	return 0
}

var File_internal_proto_lock_proto protoreflect.FileDescriptor

const file_internal_proto_lock_proto_rawDesc = "" +
	"\n" +
	"\x19internal/proto/lock.proto\x12\vlockservice\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"!\n" +
	"\vReadRequest\x12\x12\n" +
	"\x04read\x18\x01 \x01(\bR\x04read\"C\n" +
	"\fReadResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x1b\n" +
	"\tcurr_data\x18\x02 \x01(\x03R\bcurrData\"A\n" +
	"\fWriteRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x10\n" +
	"\x03val\x18\x02 \x01(\x03R\x03val\"J\n" +
	"\rWriteResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12!\n" +
	"\fupdated_data\x18\x02 \x01(\x03R\vupdatedData2\xc7\x01\n" +
	"\vLockService\x12;\n" +
	"\x04Ping\x12\x18.lockservice.PingRequest\x1a\x19.lockservice.PingResponse\x12;\n" +
	"\x04Read\x12\x18.lockservice.ReadRequest\x1a\x19.lockservice.ReadResponse\x12>\n" +
	"\x05Write\x12\x19.lockservice.WriteRequest\x1a\x1a.lockservice.WriteResponseBCZAgithub.com/username/distributed-lock-service/internal/proto;protob\x06proto3"

var (
	file_internal_proto_lock_proto_rawDescOnce sync.Once
	file_internal_proto_lock_proto_rawDescData []byte
)

func file_internal_proto_lock_proto_rawDescGZIP() []byte {
	file_internal_proto_lock_proto_rawDescOnce.Do(func() {
		file_internal_proto_lock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_lock_proto_rawDesc), len(file_internal_proto_lock_proto_rawDesc)))
	})
	return file_internal_proto_lock_proto_rawDescData
}

var file_internal_proto_lock_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_lock_proto_goTypes = []any{
	(*PingRequest)(nil),   // 0: lockservice.PingRequest
	(*PingResponse)(nil),  // 1: lockservice.PingResponse
	(*ReadRequest)(nil),   // 2: lockservice.ReadRequest
	(*ReadResponse)(nil),  // 3: lockservice.ReadResponse
	(*WriteRequest)(nil),  // 4: lockservice.WriteRequest
	(*WriteResponse)(nil), // 5: lockservice.WriteResponse
}
var file_internal_proto_lock_proto_depIdxs = []int32{
	0, // 0: lockservice.LockService.Ping:input_type -> lockservice.PingRequest
	2, // 1: lockservice.LockService.Read:input_type -> lockservice.ReadRequest
	4, // 2: lockservice.LockService.Write:input_type -> lockservice.WriteRequest
	1, // 3: lockservice.LockService.Ping:output_type -> lockservice.PingResponse
	3, // 4: lockservice.LockService.Read:output_type -> lockservice.ReadResponse
	5, // 5: lockservice.LockService.Write:output_type -> lockservice.WriteResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_lock_proto_init() }
func file_internal_proto_lock_proto_init() {
	if File_internal_proto_lock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_lock_proto_rawDesc), len(file_internal_proto_lock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_lock_proto_goTypes,
		DependencyIndexes: file_internal_proto_lock_proto_depIdxs,
		MessageInfos:      file_internal_proto_lock_proto_msgTypes,
	}.Build()
	File_internal_proto_lock_proto = out.File
	file_internal_proto_lock_proto_goTypes = nil
	file_internal_proto_lock_proto_depIdxs = nil
}
